### ISSUE TITLE
Unable to run program using either Windows or Mac Python 3.  Same error upon executing.

### ISSUE THREAD

**Issue by jaisen1** [Navy-Precision-Optial-Interferometer/erin-projects#1]
Traceback (most recent call last):
  File "C:\Users\Jsun\Downloads\erin-projects-main\offset_calculator_gui.py", line 99, in <module>
    dropdown_year = OptionMenu(frame, yearvar, *years)
TypeError: __init__() missing 1 required positional argument: 'value'

**Comment by ermaier** [comment]
Issue was that the raw text files were being read as ".sent" files due to their file naming scheme rather than ".txt" files. Code
modified to look for files that have "starLog" in the name, regardless of file extension.
